#
# https://qiita.com/kawakawaryuryu/items/b0291c1bc1141a535263#set-up-docker-buildx より
#
# セットするシークレット
# DOCKERHUB_USERNAME: DockerHub ユーザ名
# DOCKERHUB_PASSWORD: DockerHub パスワード
# DOCKER_IMAGENAME: Dockerイメージ名
#

name: Build and Publish Docker

on:
  push:
    branches:
      - "master"
      - "main"
      - "8.1"
      - "8.1-with_python3.10"
      - "8.2"
      - "8.2-with_python3.11"
      - "8.2-with_python3.12"
      - "8.3"
      - "8.3-with_python3.13"

  schedule:
    - cron: "0 0 1 * *"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        branch:
          - "master"
          - "8.1"
          - "8.1-with_python3.10"
          - "8.2"
          - "8.2-with_python3.11"
          - "8.2-with_python3.12"
          - "8.3"
          - "8.3-with_python3.13"

    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: ${{ matrix.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push(latest)
        if: contains(github.ref, 'main') || contains(github.ref, 'master')
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest

      - name: Build and push(release-${{ matrix.branch }})
        if: (!(contains(github.ref, 'main') || contains(github.ref, 'master')))
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:release-${{ env.BRANCH_NAME }}

